#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 8b93847
#
# Source0 file verified with key 0xA8041FA839E16E36 (ldv@altlinux.org)
#
Name     : Linux-PAM
Version  : 1.7.0
Release  : 65
URL      : https://github.com/linux-pam/linux-pam/releases/download/v1.7.0/Linux-PAM-1.7.0.tar.xz
Source0  : https://github.com/linux-pam/linux-pam/releases/download/v1.7.0/Linux-PAM-1.7.0.tar.xz
Source1  : https://github.com/linux-pam/linux-pam/releases/download/v1.7.0/Linux-PAM-1.7.0.tar.xz.asc
Source2  : A8041FA839E16E36.pkey
Summary  : The primary Linux-PAM library. It is used by PAM modules and PAM-aware applications.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Linux-PAM-bin = %{version}-%{release}
Requires: Linux-PAM-data = %{version}-%{release}
Requires: Linux-PAM-lib = %{version}-%{release}
Requires: Linux-PAM-license = %{version}-%{release}
Requires: Linux-PAM-locales = %{version}-%{release}
Requires: Linux-PAM-services = %{version}-%{release}
Requires: Linux-PAM-setuid = %{version}-%{release}
Requires: passwdqc
BuildRequires : autoconf
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bison-dev
BuildRequires : buildreq-meson
BuildRequires : flex-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext
BuildRequires : gettext-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnupg
BuildRequires : libeconf-dev32
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxcrypt-dev32
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(32libsystemd)
BuildRequires : pkgconfig(32systemd)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(zlib)
BuildRequires : strace
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-stateless-move-config-dist-dir.patch
Patch2: 0002-Support-altfile-locations.patch
Patch3: 0003-pam_shells-Support-a-stateless-configuration-by-defa.patch
Patch4: 0004-Add-common-pam.d-files.patch

%description
Linux-PAM (Pluggable Authentication Modules)

%package bin
Summary: bin components for the Linux-PAM package.
Group: Binaries
Requires: Linux-PAM-data = %{version}-%{release}
Requires: Linux-PAM-setuid = %{version}-%{release}
Requires: Linux-PAM-license = %{version}-%{release}
Requires: Linux-PAM-services = %{version}-%{release}

%description bin
bin components for the Linux-PAM package.


%package data
Summary: data components for the Linux-PAM package.
Group: Data

%description data
data components for the Linux-PAM package.


%package dev
Summary: dev components for the Linux-PAM package.
Group: Development
Requires: Linux-PAM-lib = %{version}-%{release}
Requires: Linux-PAM-bin = %{version}-%{release}
Requires: Linux-PAM-data = %{version}-%{release}
Provides: Linux-PAM-devel = %{version}-%{release}
Requires: Linux-PAM = %{version}-%{release}

%description dev
dev components for the Linux-PAM package.


%package dev32
Summary: dev32 components for the Linux-PAM package.
Group: Default
Requires: Linux-PAM-lib32 = %{version}-%{release}
Requires: Linux-PAM-bin = %{version}-%{release}
Requires: Linux-PAM-data = %{version}-%{release}
Requires: Linux-PAM-dev = %{version}-%{release}

%description dev32
dev32 components for the Linux-PAM package.


%package extras
Summary: extras components for the Linux-PAM package.
Group: Default

%description extras
extras components for the Linux-PAM package.


%package lib
Summary: lib components for the Linux-PAM package.
Group: Libraries
Requires: Linux-PAM-data = %{version}-%{release}
Requires: Linux-PAM-license = %{version}-%{release}

%description lib
lib components for the Linux-PAM package.


%package lib32
Summary: lib32 components for the Linux-PAM package.
Group: Default
Requires: Linux-PAM-data = %{version}-%{release}
Requires: Linux-PAM-license = %{version}-%{release}

%description lib32
lib32 components for the Linux-PAM package.


%package license
Summary: license components for the Linux-PAM package.
Group: Default

%description license
license components for the Linux-PAM package.


%package locales
Summary: locales components for the Linux-PAM package.
Group: Default

%description locales
locales components for the Linux-PAM package.


%package services
Summary: services components for the Linux-PAM package.
Group: Systemd services
Requires: systemd

%description services
services components for the Linux-PAM package.


%package setuid
Summary: setuid components for the Linux-PAM package.
Group: Default

%description setuid
setuid components for the Linux-PAM package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) A8041FA839E16E36' gpg.status
%setup -q -n Linux-PAM-1.7.0
cd %{_builddir}/Linux-PAM-1.7.0
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
pushd ..
cp -a Linux-PAM-1.7.0 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739304329
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Ddb-uniquename=_pam \
-Dnis=disabled \
-Daudit=disabled \
-Dvendordir=/usr/share/defaults/etc \
-Dsconfigdir=/usr/share/defaults/etc/security \
-Dselinux=disabled \
-Ddocs=disabled --libdir=/usr/lib64 builddir
ninja -v -C builddir
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain -Ddb-uniquename=_pam \
-Dnis=disabled \
-Daudit=disabled \
-Dvendordir=/usr/share/defaults/etc \
-Dsconfigdir=/usr/share/defaults/etc/security \
-Dselinux=disabled \
-Ddocs=disabled  builddir
ninja -v -C builddir
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/Linux-PAM
cp %{_builddir}/Linux-PAM-%{version}/COPYING %{buildroot}/usr/share/package-licenses/Linux-PAM/5fb122a984b09d5c687513bb34a51eeeff2b13a7 || :
cp %{_builddir}/Linux-PAM-%{version}/Copyright %{buildroot}/usr/share/package-licenses/Linux-PAM/5fb122a984b09d5c687513bb34a51eeeff2b13a7 || :
cp %{_builddir}/Linux-PAM-%{version}/libpamc/License %{buildroot}/usr/share/package-licenses/Linux-PAM/c6f28267889e6d36329831cfb36f80cdf4612523 || :
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang Linux-PAM
## install_append content
touch %{buildroot}/usr/share/defaults/etc/environment
install -d %{buildroot}/usr/share/pam.d/
for FILE in common-account common-auth common-password \
common-session common-session-noninteractive \
other; do
install -m 0644 $FILE %{buildroot}/usr/share/pam.d/
done

mv %{buildroot}/usr/sbin %{buildroot}/usr/bin

# The lsb requires unix_chkpwd has setuid permission
chmod 4755 %{buildroot}/usr/bin/unix_chkpwd
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/faillock
/usr/bin/mkhomedir_helper
/usr/bin/pam_namespace_helper
/usr/bin/pam_timestamp_check
/usr/bin/pwhistory_helper

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/environment
/usr/share/defaults/etc/security/access.conf
/usr/share/defaults/etc/security/faillock.conf
/usr/share/defaults/etc/security/group.conf
/usr/share/defaults/etc/security/limits.conf
/usr/share/defaults/etc/security/namespace.conf
/usr/share/defaults/etc/security/namespace.init
/usr/share/defaults/etc/security/pam_env.conf
/usr/share/defaults/etc/security/pwhistory.conf
/usr/share/defaults/etc/security/time.conf
/usr/share/pam.d/common-account
/usr/share/pam.d/common-auth
/usr/share/pam.d/common-password
/usr/share/pam.d/common-session
/usr/share/pam.d/common-session-noninteractive
/usr/share/pam.d/other

%files dev
%defattr(-,root,root,-)
/usr/include/security/_pam_compat.h
/usr/include/security/_pam_macros.h
/usr/include/security/_pam_types.h
/usr/include/security/pam_appl.h
/usr/include/security/pam_client.h
/usr/include/security/pam_ext.h
/usr/include/security/pam_filter.h
/usr/include/security/pam_misc.h
/usr/include/security/pam_modules.h
/usr/include/security/pam_modutil.h
/usr/lib64/libpam.so
/usr/lib64/libpam_misc.so
/usr/lib64/libpamc.so
/usr/lib64/pkgconfig/pam.pc
/usr/lib64/pkgconfig/pam_misc.pc
/usr/lib64/pkgconfig/pamc.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libpam.so
/usr/lib32/libpam_misc.so
/usr/lib32/libpamc.so
/usr/lib32/pkgconfig/32pam.pc
/usr/lib32/pkgconfig/32pam_misc.pc
/usr/lib32/pkgconfig/32pamc.pc
/usr/lib32/pkgconfig/pam.pc
/usr/lib32/pkgconfig/pam_misc.pc
/usr/lib32/pkgconfig/pamc.pc

%files extras
%defattr(-,root,root,-)
/usr/lib32/security/pam_filter/upperLOWER
/usr/lib64/security/pam_filter/upperLOWER

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpam.so.0
/usr/lib64/libpam.so.0.85.1
/usr/lib64/libpam_misc.so.0
/usr/lib64/libpam_misc.so.0.82.1
/usr/lib64/libpamc.so.0
/usr/lib64/libpamc.so.0.82.1
/usr/lib64/security/pam_access.so
/usr/lib64/security/pam_canonicalize_user.so
/usr/lib64/security/pam_debug.so
/usr/lib64/security/pam_deny.so
/usr/lib64/security/pam_echo.so
/usr/lib64/security/pam_env.so
/usr/lib64/security/pam_exec.so
/usr/lib64/security/pam_faildelay.so
/usr/lib64/security/pam_faillock.so
/usr/lib64/security/pam_filter.so
/usr/lib64/security/pam_ftp.so
/usr/lib64/security/pam_group.so
/usr/lib64/security/pam_issue.so
/usr/lib64/security/pam_keyinit.so
/usr/lib64/security/pam_limits.so
/usr/lib64/security/pam_listfile.so
/usr/lib64/security/pam_localuser.so
/usr/lib64/security/pam_loginuid.so
/usr/lib64/security/pam_mail.so
/usr/lib64/security/pam_mkhomedir.so
/usr/lib64/security/pam_motd.so
/usr/lib64/security/pam_namespace.so
/usr/lib64/security/pam_nologin.so
/usr/lib64/security/pam_permit.so
/usr/lib64/security/pam_pwhistory.so
/usr/lib64/security/pam_rhosts.so
/usr/lib64/security/pam_rootok.so
/usr/lib64/security/pam_securetty.so
/usr/lib64/security/pam_setquota.so
/usr/lib64/security/pam_shells.so
/usr/lib64/security/pam_stress.so
/usr/lib64/security/pam_succeed_if.so
/usr/lib64/security/pam_time.so
/usr/lib64/security/pam_timestamp.so
/usr/lib64/security/pam_umask.so
/usr/lib64/security/pam_unix.so
/usr/lib64/security/pam_usertype.so
/usr/lib64/security/pam_warn.so
/usr/lib64/security/pam_wheel.so
/usr/lib64/security/pam_xauth.so

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libpam.so.0
/usr/lib32/libpam.so.0.85.1
/usr/lib32/libpam_misc.so.0
/usr/lib32/libpam_misc.so.0.82.1
/usr/lib32/libpamc.so.0
/usr/lib32/libpamc.so.0.82.1
/usr/lib32/security/pam_access.so
/usr/lib32/security/pam_canonicalize_user.so
/usr/lib32/security/pam_debug.so
/usr/lib32/security/pam_deny.so
/usr/lib32/security/pam_echo.so
/usr/lib32/security/pam_env.so
/usr/lib32/security/pam_exec.so
/usr/lib32/security/pam_faildelay.so
/usr/lib32/security/pam_faillock.so
/usr/lib32/security/pam_filter.so
/usr/lib32/security/pam_ftp.so
/usr/lib32/security/pam_group.so
/usr/lib32/security/pam_issue.so
/usr/lib32/security/pam_keyinit.so
/usr/lib32/security/pam_limits.so
/usr/lib32/security/pam_listfile.so
/usr/lib32/security/pam_localuser.so
/usr/lib32/security/pam_loginuid.so
/usr/lib32/security/pam_mail.so
/usr/lib32/security/pam_mkhomedir.so
/usr/lib32/security/pam_motd.so
/usr/lib32/security/pam_namespace.so
/usr/lib32/security/pam_nologin.so
/usr/lib32/security/pam_permit.so
/usr/lib32/security/pam_pwhistory.so
/usr/lib32/security/pam_rhosts.so
/usr/lib32/security/pam_rootok.so
/usr/lib32/security/pam_securetty.so
/usr/lib32/security/pam_setquota.so
/usr/lib32/security/pam_shells.so
/usr/lib32/security/pam_stress.so
/usr/lib32/security/pam_succeed_if.so
/usr/lib32/security/pam_time.so
/usr/lib32/security/pam_timestamp.so
/usr/lib32/security/pam_umask.so
/usr/lib32/security/pam_unix.so
/usr/lib32/security/pam_usertype.so
/usr/lib32/security/pam_warn.so
/usr/lib32/security/pam_wheel.so
/usr/lib32/security/pam_xauth.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Linux-PAM/5fb122a984b09d5c687513bb34a51eeeff2b13a7
/usr/share/package-licenses/Linux-PAM/c6f28267889e6d36329831cfb36f80cdf4612523

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/pam_namespace.service

%files setuid
%defattr(-,root,root,-)
%attr(4755, root, root) /usr/bin/unix_chkpwd

%files locales -f Linux-PAM.lang
%defattr(-,root,root,-)

